# pyborg irc module config file
# Reported "real name"
realname = "Pyborg"
# The bot"s nickname
nickname = "PyBorg"

# Hide the fact we are a bot
stealth = false

# Channels to speak in always
speakingchans = ["#test"]
# password for control the bot (Edit manually !)
password = ""
# Reply to ignored people
reply2ignored = false
# Allow the bot to talk on channels
speaking = true
# IRC quit message
quitmsg = "Bye :-("
# Connect to pyborg instance over http for shared db?
multiplex = true
multiplex_server = "localhost"
# List of global trigger words. Supports regular expressions.
# Put "(?-i)" before a word to make it case insensitive.
trigger_words = ["(?i)Pyborg", "(?i)example"]
# % chance for trigger words, add one for each word.
trigger_chance = [100, 0]
[server]
    server = "chat.freenode.net"
    port = 6697
    password = ""
    ssl = true
    nickserv_password = "password"
    # Owner(s) nickname
    owners = ["jrabbit"]
    # Ignore these nicknames:
    ignorelist  = []
    # Channels to auto-join
    [[server.channels]]
        chan = "#ranarchism"
        speaking = true
        # Chance of reply (%) per message
        reply_chance = 5
        # List of channel-specific trigger words. Supports regular expressions.
        # Put "(?-i)" before a word to make it case insensitive.
        trigger_words = ["example", "(?i)words"]
        # % chance for trigger words, add one for each word.
        trigger_chance = [0, 0]
    [[server.channels]]
        chan = "#queertoo"
        speaking = false
        # Chance of reply (%) per message
        reply_chance = 5
        # List of channel-specific trigger words. Supports regular expressions.
        # Put "(?-i)" before a word to make it case insensitive.
        trigger_words = ["example", "(?i)words"]
        # % chance for trigger words, add one for each word.
        trigger_chance = [0, 0]



